name: Build

on:
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [18.x]
        os: [ubuntu-latest]

    name: Build - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Use Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38"
      - name: Install Node Dependencies
        run: yarn
      - name: Install Perl Dependencies
        run: yarn push:artifacts:cpanm
      - name: Build Extensions
        run: yarn build
      - name: Generate Artifacts
        run: yarn push:artifacts:generate
      - name: Checkout -> Artifacts
        uses: actions/checkout@v4
        with:
          ref: artifacts
          path: artifacts
      - name: Publish Artifacts
        run: |
          ./scripts/artifacts/clean/main.sh
          perl ../scripts/artifacts/publish/main.pl
